name: CI & Deploy

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install modules
        run: npm ci --force

      - name: Run ESLint
        run: npx eslint .

      - name: Run Prettier
        run: npx prettier --check .
